# .cirrus.yml — FreeBSD build sanity for restoHack

task:
  name: FreeBSD build (curses sanity)
  freebsd_instance:
    image_family: freebsd-14-2

  env:
    MAKEFLAGS: -j$(sysctl -n hw.ncpu)
    CIRRUS_CLONE_DEPTH: "1"

  checkout_script:
    - git clone --depth 1 "$CIRRUS_REPO_CLONE_URL" src
    - cd src

  install_script:
    - sudo pkg update -f
    - sudo pkg install -y gmake cmake ninja pkgconf ncurses git

  build_script:
    - cd src
    - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
    - cmake --build build -j

  verify_script:
    - file src/build/hack || true
    - printf '#include <curses.h>\nint main(){initscr();endwin();return 0;}\n' > /tmp/t.c
    - cc /tmp/t.c -lcurses -o /tmp/t && /tmp/t || true
